import 'package:flutter/material.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedWallclockremovebgpreview1Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedCurrentBid\$450MillionWidget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedRightarrowremovebgpreview1Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/Generated930HrWidget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedTh1Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedTrendingArtworksWidget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedSalvatorMundibyLeonardodaVinciWidget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedRemainingTimeForBidingWidget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedRightarrowremovebgpreview2Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/artauctionappapp/generateduidesignwidget/generated/GeneratedMoreWidget.dart';

/* Frame UI Design
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUIDesignWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(48.0),
      child: Container(
        width: 390.0,
        height: 844.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(48.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(48.0),
                child: Container(
                  color: Color.fromARGB(255, 199, 190, 190),
                ),
              ),
              Positioned(
                left: 44.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 23.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 42.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 421.0,
                height: 30.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 61.0,
                child: GeneratedTrendingArtworksWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 30.0,
                child: GeneratedMoreWidget(),
              ),
              Positioned(
                left: 274.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 336.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 365.0,
                child: GeneratedTh1Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 47.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 32.0,
                child: GeneratedCurrentBid$450MillionWidget(),
              ),
              Positioned(
                left: 280.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 29.0,
                child: GeneratedRemainingTimeForBidingWidget(),
              ),
              Positioned(
                left: 57.0,
                top: 627.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 27.040000915527344,
                child: GeneratedSalvatorMundibyLeonardodaVinciWidget(),
              ),
              Positioned(
                left: 81.0,
                top: 715.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 30.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 316.0,
                top: 692.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 13.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 319.0,
                top: 693.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 14.0,
                child: Generated930HrWidget(),
              ),
              Positioned(
                left: 173.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 279.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 245.0,
                top: 715.0,
                right: null,
                bottom: null,
                width: 94.03296661376953,
                height: 30.0,
                child: GeneratedGroup16Widget(),
              ),
              Positioned(
                left: 306.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedRightarrowremovebgpreview1Widget(),
              ),
              Positioned(
                left: 117.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedRightarrowremovebgpreview2Widget(),
              ),
              Positioned(
                left: 134.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 30.0,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 252.0,
                top: 683.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedWallclockremovebgpreview1Widget(),
              )
            ]),
      ),
    ));
  }
}
